account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="account/login.html"),name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="account/logout.html"),name="logout"),
]

album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('showall/', views.showall, name='showall'),
    path("upload/", views.upload, name="upload")
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.PostListView.as_view(), name="blog-home"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/<int:pk>/update/", views.PostUpdateView.as_view(), name="post-update"),
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post-delete"),
    path("post/new/", views.PostCreateView.as_view(), name="post-create"),
]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("contact/", views.contact, name="contact"),
]

features/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("features/", views.features, name="features"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
    path("portfolio/", views.portfolio, name="portfolio"),
]

gettingstarted/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings  # メディア
from django.conf.urls.static import static  # メディア

admin.autodiscover()


# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    path("", include("blog.urls")),
    path("", include("account.urls")),
    path("", include("features.urls")),
    path("", include("contact.urls")),
    path('album/', include('album.urls')),
    path("admin/", admin.site.urls),
]

# 開発環境次のみDjangoアプリケーション側でメディアファイルを配信
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

album/models.py
from django.db import models


class Image(models.Model):
    picture = models.ImageField(upload_to="images/")
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"pk": self.pk})

contact/models.py
from django.db import models

# Create your models here.

features/models.py
from django.db import models

# Create your models here.

album/forms.py
from django import forms
from .models import Image


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['picture', 'title']

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
    else:
        form = UserCreationForm()
    return render(request, "account/signup.html", {"form": form})

album/views.py
from django.shortcuts import render, redirect
from .models import Image
from .forms import ImageForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def showall(request):
    images = Image.objects.all()
    context = {'images': images}
    return render(request, 'album/showall.html', context)


def upload(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('album:showall')
    else:
        form = ImageForm()

    context = {'form': form}
    return render(request, 'album/upload.html', context)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Post


class PostListView(ListView):
    model = Post
    paginate_by = 3
    template_name = "blog/home.html"
    context_object_name = "posts"
    ordering = ["-date_posted"]


class PostDetailView(DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ["title", "content"]
    success_url = "/"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ["title", "content"]
    success_url = "/"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = "/"

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

contact/views.py
from django.shortcuts import render

def contact(request):
    return render(request, 'contact/contact.html')

features/views.py
from django.shortcuts import render

def features(request):
    return render(request, 'features/features.html')

def about(request):
    return render(request, "features/about.html")

def faq(request):
    return render(request, "features/faq.html")

def portfolio(request):
    return render(request, "features/portfolio.html")

album/templates/album/showall.html
{% extends "account/base.html" %}
{% load crispy_forms_tags %}
{% load cloudinary %}
{% load static %}

<body id="wrapper">

    {% block body %}

    <section id="top_banner">
        <div class="banner">
            <div class="inner text-center">
                <h2>投稿ページ</h2>
            </div>
        </div>
        <div class="page_info">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-8 col-xs-6">
                        <h4>動画や画像を投稿できるよ！</h4>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-6" style="text-align:right;">Home<span class="sep"> /
                        </span><span class="current">Portfolio</span></div>
                </div>
            </div>
        </div>

        </div>
    </section>

    <section id="portfolio">
        <div class="container">
            <div class="row">
                <div class="section-heading text-center">
                    <div class="col-md-12 col-xs-12">
                        <h1>simple <span>tube</span></h1>
                        <h2><a href="{% url 'album:upload' %}">ここから投稿してね！</a></h2>
                        {% for post in object_list %}
                        {% cloudinary post.image.url width=300 height=150 %}
                        {% endfor %}
                        何もない
                        <hr>
                    </div>
                </div>
            </div>

            {% for image in images %}
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 portfolio-item">
                    <div class="portfolio-one">
                        <div class="portfolio-head">
                            <div class="portfolio-img"><img alt="" src='{{ MEDIA_URL }}{{image.picture}}'>
                            </div>
                            <div class="portfolio-hover">
                                <a class="portfolio-link" href="#"><i class="fa fa-link"></i></a>
                                <a class="portfolio-zoom" href="#"><i class="fa fa-search"></i></a>
                            </div>
                        </div>
                        <!-- End portfolio-head -->
                        <div class="portfolio-content">
                            <h5 class="title">画像</h5>
                            <p>投稿</p>
                        </div>
                        <!-- End portfolio-content -->
                    </div>
                    <!-- End portfolio-item -->
                </div>
            </div>
            {% endfor %}

        </div>

    </section>

    {% endblock body %}

</body>

album/templates/album/upload.html
{% extends "account/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block body %}
<center>
    <h1>Please Upload</h1>

    <form enctype="multipart/form-data" action="{% url 'album:upload' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Upload">
    </form>
</center>

{% endblock body %}

blog/templates/blog/post_confirm_delete.html
{% extends "account/base.html" %}


{% block body %}    
<center>

<div class="col-md-6 col-sm-12">
    <div class="form-box">
        <div class="form-top">
            <div class="form-top-left">
                <h3>Delete</h3>
                <p>本当に「{{ object.title }}」を削除しますか？</p>
            </div>
            <div class="form-top-right">
                <i class="fa fa-pencil"></i>
            </div>
        </div>
        <div class="form-bottom">
            <form method="POST" role="form" action="" class="login-form">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </div>

</div>

</center>
{% endblock body %}

blog/templates/blog/post_detail.html
{% extends "account/base.html" %} {% block body %}
<center>
  <h1>
    {{ object.title }} <small>written by </small
    ><span>{{ object.author }}</span>
  </h1>
  <p class="subheading">{{ object.date_posted|date:"Y-m-d P" }}</p>

  <ul class="aboutul">
    <li>{{ object.content | linebreaksbr }}</li>
  </ul>
  <hr />

  <form action="{% url 'post-update' post.id %}">
    <button type="submit" class="btn btn-success slide">Update</button>
  </form>
  <br />
  <form action="{% url 'post-delete' post.id %}">
    <button type="submit" class="btn btn-danger slide">Delete</button>
  </form>
</center>
{% endblock body %}

blog/templates/blog/post_form.html
{% extends "account/base.html" %} {% load crispy_forms_tags %} {% block body%}

<div class="col-md-6 col-sm-12">
  <div class="form-box">
    <div class="form-top">
      <div class="form-top-left">
        <h3>New Post</h3>
        <p>Fill in the form below to get instant access</p>
      </div>
      <div class="form-top-right">
        <i class="fa fa-pencil"></i>
      </div>
    </div>
    <div class="form-bottom">
      <form method="POST" role="form" action="" class="login-form">
        {% csrf_token %} {{ form | crispy }}
        <button type="submit" class="btn btn-primary">Post Now</button>
      </form>
    </div>
  </div>
</div>

{% block foot %} {% endblock foot %} {% endblock body %}

contact/templates/contact/contact.html
{% extends "account/base.html" %}
{% load static %}

<body id="wrapper">

    {% block body %}

    <section id="top_banner">
        <div class="banner">
            <div class="inner text-center">
                <h2>連絡はここから！</h2>
            </div>
        </div>
        <div class="page_info">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-8 col-xs-6">
                        <h4>Contact</h4>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-6" style="text-align:right;">Home<span class="sep"> / </span><span class="current">Contact</span></div>
                </div>
            </div>
        </div>

        </div>
    </section>
    <section id="contact-page">
        <div class="container">
            <div class="section-heading text-center">
                <h2>Drop your <span>Message</span></h2>
                <p class="subheading">何でも聞いてね！</p>
            </div>
            <div class="row contact-wrap">
                <div class="status alert alert-success" style="display: none"></div>
                <form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="sendemail.php">
                    <div class="col-sm-5 col-sm-offset-1">
                        <div class="form-group">
                            <label>Name *</label>
                            <input type="text" name="name" class="form-control" required="required">
                        </div>
                        <div class="form-group">
                            <label>Email *</label>
                            <input type="email" name="email" class="form-control" required="required">
                        </div>
                        <div class="form-group">
                            <label>Phone</label>
                            <input type="number" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Company Name</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group">
                            <label>Subject *</label>
                            <input type="text" name="subject" class="form-control" required="required">
                        </div>
                        <div class="form-group">
                            <label>Message *</label>
                            <textarea name="message" id="message" required="required" class="form-control" rows="8"></textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" name="submit" class="btn btn-default submit-button">Submit Message <i class="fa fa-caret-right"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <section id="contact">
        <div class="overlay">
            <div class="gmap-area">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-5">
                            <div class="gmap">
                                <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=JoomShaper,+Dhaka,+Dhaka+Division,+Bangladesh&amp;aq=0&amp;oq=joomshaper&amp;sll=37.0625,-95.677068&amp;sspn=42.766543,80.332031&amp;ie=UTF8&amp;hq=JoomShaper,&amp;hnear=Dhaka,+Dhaka+Division,+Bangladesh&amp;ll=23.73854,90.385504&amp;spn=0.001515,0.002452&amp;t=m&amp;z=14&amp;iwloc=A&amp;cid=1073661719450182870&amp;output=embed"></iframe>
                            </div>
                        </div>
                        <div class="col-sm-7 map-content">
                            <ul class="row">
                                <li class="col-sm-6">
                                    <address>
									<h5>Head Office</h5>
									<p>Aspire Software Solutions <br>
									202, Parishram Complex,<br>
									Mithakhali Six Roads,<br>
									Navrangpura, Ahmedabad,<br>
									Gujarat, India. </p>
										<p>Phone:+91 848 594 5080 <br>
									Email Address:sales@aspiresoftware.in</p>
								</address>

                                </li>
                                <li class="col-sm-6">
                                    <address>
									<h5>Zone#2 Office</h5>
									<p>Aspire Software Solutions <br>
									202, Parishram Complex,<br>
									Mithakhali Six Roads,<br>
									Navrangpura, Ahmedabad,<br>
									Gujarat, India. </p>
									<p>Phone:+91 848 594 5080 <br>
									Email Address:sales@aspiresoftware.in</p>
								</address>

                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% endblock body %}

</body>

features/templates/features/faq.html
{% extends "account/base.html" %}
{% load static %}

<body id="wrapper">

    {% block body %}

    <section id="top_banner">
        <div class="banner">
            <div class="inner text-center">
                <h2>何が知りたい？？</h2>
            </div>
        </div>
        <div class="page_info">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-8 col-xs-6">
                        <h4>FAQ</h4>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-6" style="text-align:right;">Home<span class="sep"> 	/ </span><span class="current"> FAQ</span></div>
                </div>
            </div>
        </div>

        </div>
    </section>


    <section id="faq">
        <div class="titlebar">
            <div class="container">
                <div class="row">
                    <div class="section-heading text-center">
                        <div class="col-md-12 col-xs-12">
                            <h2>Know Us <span>More</span></h2>
                            <p class="subheading">詳細</p>
                        </div>
                    </div>
                </div>



                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                    <div class="rich-accordian">
                        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingOne">
                                    <h4 class="panel-title">
                                        <div class="icon-circle"> <i class="fa fa-cog"></i></div>
                                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    How do I purchase your product?
                                    </a>
                                    </h4>
                                </div>
                                <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                                    <div class="panel-body">
                                        Lorem ipsum dolor sit amet, sed in nostro latine, eu option appetere mediocritatem duo. Pro duis magna perpetua ea. Dicant epicurei gubergren eos ne, ad suas ornatus graecis nam, pri quot liber ignota no. Usu et erat propriae invenire, blandit voluptua
                                        vim at, iuvaret albucius cu ius. Te integre diceret praesent eos, impetus legimus te vim. Ne mollis veritus est.
                                    </div>
                                </div>
                            </div>

                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingTwo">
                                    <h4 class="panel-title">
                                        <div class="icon-circle"> <i class="fa fa-desktop"></i></div>
                                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                     Do you provide product support?
                                    </a>
                                    </h4>
                                </div>
                                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                    <div class="panel-body">
                                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute
                                    </div>
                                </div>
                            </div>

                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingThree">
                                    <h4 class="panel-title">
                                        <div class="icon-circle"> <i class="fa fa-magic"></i></div>
                                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                     Can I change the theme color?
                                    </a>
                                    </h4>
                                </div>
                                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                                    <div class="panel-body">
                                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                    <div class="rich-accordian">
                        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingfour">
                                    <h4 class="panel-title">
                                        <div class="icon-circle"> <i class="fa fa-cloud-download"></i></div>
                                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapsefour" aria-expanded="true" aria-controls="collapsefour">
                                   How to download source files
                                    </a>
                                    </h4>
                                </div>
                                <div id="collapsefour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingfour">
                                    <div class="panel-body">
                                        Lorem ipsum dolor sit amet, sed in nostro latine, eu option appetere mediocritatem duo. Pro duis magna perpetua ea. Dicant epicurei gubergren eos ne, ad suas ornatus graecis nam, pri quot liber ignota no. Usu et erat propriae invenire, blandit voluptua
                                        vim at, iuvaret albucius cu ius. Te integre diceret praesent eos, impetus legimus te vim. Ne mollis veritus est.
                                    </div>
                                </div>
                            </div>

                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingfive">
                                    <h4 class="panel-title">
                                        <div class="icon-circle"> <i class="fa fa-fonticons"></i></div>
                                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapsefive" aria-expanded="false" aria-controls="collapsefive">
                                    How to download and use icons
                                    </a>
                                    </h4>
                                </div>
                                <div id="collapsefive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingfive">
                                    <div class="panel-body">
                                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute
                                    </div>
                                </div>
                            </div>

                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingsix">
                                    <h4 class="panel-title">
                                        <div class="icon-circle"> <i class="fa fa-fonticons"></i></div>
                                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapsesix" aria-expanded="false" aria-controls="collapsesix">
                                    How to organise icons to Projects
                                    </a>
                                    </h4>
                                </div>
                                <div id="collapsesix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingsix">
                                    <div class="panel-body">
                                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

    {% endblock body %}

</body>